CREATE TABLE "fda_guidances" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"title" varchar(512) NOT NULL,
	"type" varchar(100),
	"status" varchar(50),
	"center" varchar(50),
	"office" varchar(100),
	"topic" varchar(255),
	"docket_number" varchar(100),
	"issue_date" timestamp,
	"comment_opening_date" timestamp,
	"comment_closing_date" timestamp,
	"supersedes" jsonb,
	"superseded_by" jsonb,
	"related_guidances" jsonb,
	"official_pdf_url" text,
	"federal_register_notice_url" text,
	"source_url" text,
	"ai_executive_summary" jsonb,
	"ai_diff_analysis" jsonb,
	"ai_regulatory_impact" jsonb,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "fda_guidances_docket_number_unique" UNIQUE("docket_number")
);
